4 TO - DO - Task

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.


Problem - 1: Array Creation:

In [1]:
import numpy as np

# 1. Empty 2x2 array
empty_array = np.empty((2, 2))
print("Empty 2x2 Array:\n", empty_array)

# 2. All ones 4x2 array
ones_array = np.ones((4, 2))
print("\nAll Ones 4x2 Array:\n", ones_array)

# 3. Array with specific fill value
filled_array = np.full((3, 3), 7)
print("\n3x3 Array Filled with 7:\n", filled_array)

# 4. Zeros array with same shape as another
array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(array)
print("\nZeros Array with Same Shape as Array:\n", zeros_like_array)

# 5. Ones array with same shape as another
ones_like_array = np.ones_like(array)
print("\nOnes Array with Same Shape as Array:\n", ones_like_array)

# 6. Convert list to NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nList Converted to NumPy Array:\n", numpy_array)

print("\n" + "-" * 50 + "\n")


Empty 2x2 Array:
 [[4.89770928e-310 0.00000000e+000]
 [2.60746796e+081 6.94404827e-310]]

All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3x3 Array Filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Array:
 [[0 0]
 [0 0]]

Ones Array with Same Shape as Array:
 [[1 1]
 [1 1]]

List Converted to NumPy Array:
 [1 2 3 4]

--------------------------------------------------



Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [2]:
# 1. Array from 10 to 49
arr = np.arange(10, 50)
print("Array from 10 to 49:\n", arr)

# 2. 3x3 matrix reshaped from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix Reshaped from 0 to 8:\n", matrix)

# 3. 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Random array of size 30
random_array = np.random.random(30)
print("\nRandom Array of Size 30:\n", random_array)
print("Mean:", random_array.mean())

# 5. 10x10 random array with min and max
array_10x10 = np.random.random((10, 10))
print("\n10x10 Random Array:\n", array_10x10)
print("Min:", array_10x10.min(), "Max:", array_10x10.max())

# 6. Zero array of size 10 with 5th element as 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with Fifth Element as 1:\n", zero_array)

# 7. Reverse an array
arr_to_reverse = [1, 2, 0, 0, 4, 0]
reversed_array = arr_to_reverse[::-1]
print("\nReversed Array:\n", reversed_array)

# 8. 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)

print("\n" + "-" * 50 + "\n")

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix Reshaped from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of Size 30:
 [0.56731312 0.20691242 0.64058835 0.87515235 0.82891097 0.17192574
 0.78326077 0.55302087 0.9384584  0.60118311 0.00870836 0.93266577
 0.85217624 0.0150231  0.16529258 0.76416373 0.78407229 0.77914791
 0.78132019 0.63388448 0.15459057 0.35077014 0.59389858 0.3090604
 0.95951765 0.08071581 0.26666801 0.54602368 0.22616835 0.93314302]
Mean: 0.5434578992077131

10x10 Random Array:
 [[0.47670712 0.66575847 0.57675452 0.21450899 0.57515314 0.6837775
  0.28951513 0.78086867 0.80048698 0.54725971]
 [0.46782177 0.51026602 0.06084643 0.52847562 0.70124546 0.9192601
  0.60541479 0.95566109 0.43093002 0.20540488]
 [0.71592852 0.76074684 0.02261175 0.41585074 0.67268966 0.96611752
  0.44685644 0.97812371 0.4

Problem - 3: Array Operations:

In [3]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
result_add = np.add(x, y)
print("Addition of x and y:\n", result_add)

# 2. Subtract the two arrays
result_subtract = np.subtract(x, y)
print("\nSubtraction of x and y:\n", result_subtract)

# 3. Multiply the array with any integer
result_multiply = x * 2
print("\nMultiplication of x by 2:\n", result_multiply)

# 4. Find the square of each element
result_square = np.square(x)
print("\nSquare of each element in x:\n", result_square)

# 5. Dot product
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\nDot Product (v.w):", dot_v_w)
print("Dot Product (x.v):\n", dot_x_v)
print("Dot Product (x.y):\n", dot_x_y)

# 6. Concatenate x and y along rows and v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("\nConcatenate x and y along rows:\n", concat_xy)
print("Concatenate v and w along columns:\n", concat_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError in concatenating x and v:", e)
    print("Explanation: Cannot concatenate arrays with mismatched dimensions.")

print("\n" + "-" * 50 + "\n")



Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot Product (v.w): 219
Dot Product (x.v):
 [29 77]
Dot Product (x.y):
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Cannot concatenate arrays with mismatched dimensions.

--------------------------------------------------



Problem - 4: Matrix Operations:

In [4]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1:\n", identity)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("Are (AB)^T and B^T * A^T equal?", np.array_equal(AB_T, BT_AT))

# 4. Solve the system of linear equations
coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])

solutions = np.linalg.solve(coefficients, constants)
print("\nSolution to the system of equations:\n", solutions)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal? False

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal? True

Solution to the system of equations:
 [ 2.  1. -2.]
